CREATE TABLE users
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) UNIQUE NOT NULL,
    password varchar             NOT NULL,
    birthday DATE                NOT NULL,
    email    varchar(100) UNIQUE NOT NULL,
    address  varchar(100)        NOT NULL
);

INSERT INTO users(username, password, birthday, email, address)
VALUES ('login1', 'ffytfty', '1999-08-06', 'gygyu@mail.ru', 'Pushkina 54')