CREATE TABLE users
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) UNIQUE NOT NULL,
    password varchar             NOT NULL,
    birthday DATE                NOT NULL,
    email    varchar(100) UNIQUE NOT NULL,
    address  varchar(100)        NOT NULL
);

INSERT INTO users (username, password, birthday, email, address)
VALUES
    ('john_doe', 'P@ssw0rd', '1985-05-15', 'john.doe@example.com', '123 Main Street, Cityville'),
    ('jane_smith', 'Secure123', '1990-02-28', 'jane.smith@example.com', '456 Oak Avenue, Townsville'),
    ('alex_miller', 'SecretPass', '1988-09-10', 'alex.miller@example.com', '789 Pine Road, Villagetown'),
    ('emily_jones', 'MyP@ssword', '1982-12-03', 'emily.jones@example.com', '101 Cedar Lane, Hamletville'),
    ('michael_brown', 'Brownie123', '1995-07-20', 'michael.brown@example.com', '202 Elm Street, Villageton'),
    ('susan_wilson', 'StrongP@ss', '1980-11-18', 'susan.wilson@example.com', '303 Birch Avenue, Citytown'),
    ('david_clark', 'Clark123', '1987-04-08', 'david.clark@example.com', '404 Maple Road, Township'),
    ('laura_adams', 'AdamsPass', '1993-08-25', 'laura.adams@example.com', '505 Oak Lane, Villageville'),
    ('kevin_morris', 'KevPass123', '1984-06-12', 'kevin.morris@example.com', '606 Pine Street, Hamletton'),
    ('natalie_gomez', 'N@talie2022', '1989-01-30', 'natalie.gomez@example.com', '707 Cedar Avenue, Towneton');
