CREATE TABLE users
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) UNIQUE NOT NULL,
    password varchar             NOT NULL,
    birthday int                 NOT NULL,
    mail     varchar(100) UNIQUE NOT NULL
);

INSERT INTO users(username, password, birthday, mail)
VALUES ('login1', 'ffytfty', 1955, 'gygyu@mail.ru')